package com.tririga.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-04-30T12:18:29.756+05:30
 * Generated source version: 3.5.0
 */

@WebFault(name = "ActionItemInvalidException", targetNamespace = "http://ws.tririga.com")
public class ActionItemInvalidException extends java.lang.Exception {

    private com.tririga.ws.errors.ActionItemInvalidException faultInfo;

    public ActionItemInvalidException() {
        super();
    }

    public ActionItemInvalidException(String message) {
        super(message);
    }

    public ActionItemInvalidException(String message, Throwable cause) {
        super(message, cause);
    }

    public ActionItemInvalidException(String message, com.tririga.ws.errors.ActionItemInvalidException actionItemInvalidException) {
        super(message);
        this.faultInfo = actionItemInvalidException;
    }

    public ActionItemInvalidException(String message, com.tririga.ws.errors.ActionItemInvalidException actionItemInvalidException, Throwable cause) {
        super(message, cause);
        this.faultInfo = actionItemInvalidException;
    }

    public com.tririga.ws.errors.ActionItemInvalidException getFaultInfo() {
        return this.faultInfo;
    }
}
