package com.tririga.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-04-30T12:18:29.687+05:30
 * Generated source version: 3.5.0
 */

@WebFault(name = "ActionDoesNotExistException", targetNamespace = "http://ws.tririga.com")
public class ActionDoesNotExistException extends java.lang.Exception {

    private com.tririga.ws.errors.ActionDoesNotExistException faultInfo;

    public ActionDoesNotExistException() {
        super();
    }

    public ActionDoesNotExistException(String message) {
        super(message);
    }

    public ActionDoesNotExistException(String message, Throwable cause) {
        super(message, cause);
    }

    public ActionDoesNotExistException(String message, com.tririga.ws.errors.ActionDoesNotExistException actionDoesNotExistException) {
        super(message);
        this.faultInfo = actionDoesNotExistException;
    }

    public ActionDoesNotExistException(String message, com.tririga.ws.errors.ActionDoesNotExistException actionDoesNotExistException, Throwable cause) {
        super(message, cause);
        this.faultInfo = actionDoesNotExistException;
    }

    public com.tririga.ws.errors.ActionDoesNotExistException getFaultInfo() {
        return this.faultInfo;
    }
}
