package com.tririga.ws;

import javax.xml.bind.annotation.XmlType;
import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-04-30T12:18:29.515+05:30
 * Generated source version: 3.5.0
 */

@WebFault(name = "Exception", targetNamespace = "http://ws.tririga.com")
@XmlType(name = "Exception", namespace = "http://ws.tririga.com")
public class Exception extends java.lang.Exception {

    private java.lang.Exception faultInfo;

    public Exception() {
        super();
    }

    public Exception(String message) {
        super(message);
    }

    public Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception(String message, java.lang.Exception exception) {
        super(message);
        this.faultInfo = exception;
    }

    public Exception(String message, java.lang.Exception exception, Throwable cause) {
        super(message, cause);
        this.faultInfo = exception;
    }

    public java.lang.Exception getFaultInfo() {
        return this.faultInfo;
    }
}
