package com.tririga.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-04-30T12:18:29.753+05:30
 * Generated source version: 3.5.0
 */

@WebFault(name = "GuiDoesNotExistException", targetNamespace = "http://ws.tririga.com")
public class GuiDoesNotExistException extends java.lang.Exception {

    private com.tririga.ws.errors.GuiDoesNotExistException faultInfo;

    public GuiDoesNotExistException() {
        super();
    }

    public GuiDoesNotExistException(String message) {
        super(message);
    }

    public GuiDoesNotExistException(String message, Throwable cause) {
        super(message, cause);
    }

    public GuiDoesNotExistException(String message, com.tririga.ws.errors.GuiDoesNotExistException guiDoesNotExistException) {
        super(message);
        this.faultInfo = guiDoesNotExistException;
    }

    public GuiDoesNotExistException(String message, com.tririga.ws.errors.GuiDoesNotExistException guiDoesNotExistException, Throwable cause) {
        super(message, cause);
        this.faultInfo = guiDoesNotExistException;
    }

    public com.tririga.ws.errors.GuiDoesNotExistException getFaultInfo() {
        return this.faultInfo;
    }
}
