package com.tririga.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-04-30T12:18:29.767+05:30
 * Generated source version: 3.5.0
 */

@WebFault(name = "ListDoesNotExistException", targetNamespace = "http://ws.tririga.com")
public class ListDoesNotExistException extends java.lang.Exception {

    private com.tririga.ws.errors.ListDoesNotExistException faultInfo;

    public ListDoesNotExistException() {
        super();
    }

    public ListDoesNotExistException(String message) {
        super(message);
    }

    public ListDoesNotExistException(String message, Throwable cause) {
        super(message, cause);
    }

    public ListDoesNotExistException(String message, com.tririga.ws.errors.ListDoesNotExistException listDoesNotExistException) {
        super(message);
        this.faultInfo = listDoesNotExistException;
    }

    public ListDoesNotExistException(String message, com.tririga.ws.errors.ListDoesNotExistException listDoesNotExistException, Throwable cause) {
        super(message, cause);
        this.faultInfo = listDoesNotExistException;
    }

    public com.tririga.ws.errors.ListDoesNotExistException getFaultInfo() {
        return this.faultInfo;
    }
}
